
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('users').del()
    .then(function () {
      // Inserts seed entries
      return Promise.all([
        knex('users').insert({email: 'test1@test.com', password: 'Test12345', first_name: 'Jon', last_name: 'Doe', gender: 'M', user_city: 'Seattle', user_country: 'United States', user_bio: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi temp', user_influence: 'Michael Jackson', soundcloud_link: 'https://soundcloud.com/reggiewatts/gopher-cheeks-on-life-quantum', isAvailable: 1, looking_for: 'Singer'}),
        knex('users').insert({email: 'test2@test.com', password: 'Test12345', first_name: 'Mercury', last_name: 'Long', gender: 'M', user_city: 'Toronto', user_country: 'Canada', user_bio: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibu', user_influence: 'Madonna', soundcloud_link: 'https://soundcloud.com/guitarworld/acousticnation-april2017-3', isAvailable: 1, looking_for: 'Electric Guitar'}),
        knex('users').insert({email: 'test3@test.com', password: 'Test12345', first_name: 'Saturn', last_name: 'Short', gender: 'M', user_city: 'Los Angeles', user_country: 'United States', user_bio: '', user_influence: 'Metallica', soundcloud_link: 'https://soundcloud.com/fifiandjules/what-we-learned-about-jules-2', isAvailable: 0, looking_for: ''}),
        knex('users').insert({email: 'test4@test.com', password: 'Test12345', first_name: 'Gene', last_name: 'Moto', gender: 'F', user_city: 'Vancouver', user_country: 'Canada', user_bio: 'The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words. Everyone realizes why a new common language would be desirable: one could refuse to pay expensive translators. To achieve this, it would be necessary to have uniform grammar, pronunciation and more common words. If several languages coalesce, the gram', user_influence: 'Justin Timberlake', soundcloud_link: '', isAvailable: 0, looking_for: ''}),
        knex('users').insert({email: 'test5@test.com', password: 'Test12345', first_name: 'Sam', last_name: 'Winchester', gender: 'M', user_city: 'Texas', user_country: 'Texas', user_bio: 'The quick, brown fox jumps over a lazy dog. DJs flock by', user_influence: 'Jimi Hendrix', soundcloud_link: '', isAvailable: 1, looking_for: 'Violin'}),
        knex('users').insert({email: 'test6@test.com', password: 'Test12345', first_name: 'Laura', last_name: 'Gould', gender: 'F', user_city: 'San Francisco', user_country: 'United States', user_bio: 'Just checking if there is any opportunity out there.', user_influence: 'Bob Marley', soundcloud_link: 'https://soundcloud.com/reggiewatts/gopher-cheeks-on-life-quantum', isAvailable: 1, looking_for: 'Piano'}),
        knex('users').insert({email: 'test7@test.com', password: 'Test12345', first_name: 'Jane', last_name: 'Renault', gender: 'F', user_city: 'Edmonton', user_country: 'Canada', user_bio: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibu', user_influence: 'Charlie Parker', soundcloud_link: '', isAvailable: 0, looking_for: ''}),
        knex('users').insert({email: 'test8@test.com', password: 'Test12345', first_name: 'Dave', last_name: 'McDonald', gender: 'M', user_city: 'Calgary', user_country: 'Canada', user_bio: '', user_influence: 'Ylvis', soundcloud_link: 'https://soundcloud.com/fifiandjules/what-we-learned-about-jules-2', isAvailable: 0, looking_for: ''}),
        knex('users').insert({email: 'test9@test.com', password: 'Test12345', first_name: 'Lucy', last_name: 'Liu', gender: 'F', user_city: 'New York', user_country: 'United States', user_bio: 'The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words. Everyone realizes why a new common language would be desirable: one could refuse to pay expensive translators. To achieve this, it would be necessary to have uniform grammar, pronunciation and more common words. If several languages coalesce, the gram', user_influence: 'Katy Perry', soundcloud_link: '', isAvailable: 1, looking_for: 'Singer'}),
        knex('users').insert({email: 'test10@test.com', password: 'Test12345', first_name: 'Dean', last_name: 'Findle', gender: 'M', user_city: 'Montreal', user_country: 'Canada', user_bio: 'The quick, brown fox jumps over a lazy dog. DJs flock by when MTV ax quiz prog. Junk MTV quiz graced by fox whelps. Bawds jog, flick quartz, vex nymphs. Waltz, bad nymph, for quick jigs vex! Fox nymphs grab quick-jived waltz. Brick quiz whangs jumpy veldt fox. Bright vixens jump; dozy fowl quack. Quick wafting zephyrs vex bold Jim. Quick zephyrs blow, vexing daft Jim. Sex-charged fop blew my junk TV quiz. How quickly daft jumping zebras vex. Two driven jocks help fax my big quiz. Quick, Baz, get', user_influence: 'Eminem', soundcloud_link: 'https://soundcloud.com/fifiandjules/what-we-learned-about-jules-2', isAvailable: 1, looking_for: 'Drum'})
      ]);
    });
};
